env:
  node: true
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
