language: node_js
node_js:
- "6"
services:
- postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - sequelize db:migrate
env:
  global:
    - export NODE_ENV=test
script:
- npm test
- npm run coverage
- npm install
after_success: 'npm run coveralls'