language: node_js
node_js:
- "6"
services:
- postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - sequelize db:migrate
env:
  global:
    - export NODE_ENV=test
    - export SECRET_KEY = '#1001-tapsuk-bis-bellal;kajd;lf9u2309ruld;fa '
script:
- npm install
- npm test
- npm run coverage
after_success: 'npm run coveralls'
