// Users Action Types
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';

export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_PASSWORD_ERROR = 'UPDATE_USER_PASSWORD_ERROR';

export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const GET_USER_RECIPES_ERROR = 'GET_USER_RECIPES_ERROR';

// Recipe Action types

export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE';
export const ADD_NEW_RECIPE_ERROR = 'ADD_NEW_RECIPE_ERROR';

export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ALL_RECIPES_ERROR = 'GET_ALL_RECIPES_ERROR';

export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';
export const GET_RECIPE_DETAILS_ERROR = 'GET_RECIPE_DETAILS_ERROR';

export const EDIT_RECIPE = 'EDIT_RECIPE';
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR';

export const DELETE_RECIPE = 'DELETE_RECIPE';
export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR';

export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const SEARCH_RECIPE_ERROR = 'SEARCH_RECIPE_ERROR';

export const POPULAR_RECIPE = 'POPULAR_RECIPE';
export const POPULAR_RECIPE_ERROR = 'POPULAR_RECIPE_ERROR';

// Recipe Review Actions types
// *** Favorites
export const FAVORITE_RECIPE = 'FAVORITE_RECIPE';
export const FAVORITE_RECIPE_ERROR = 'FAVORITE_RECIPE_ERROR';

export const GET_FAVORITE_RECIPES = 'GET_FAVORITE_RECIPES';
export const GET_FAVORITE_RECIPES_ERROR = 'GET_FAVORITE_RECIPES_ERROR';

export const GET_RECIPE_REVIEW = 'GET_RECIPE_REVIEW';
export const GET_RECIPE_REVIEW_ERROR = 'GET_RECIPE_REVIEW_ERROR';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR';

// *** Votes
export const VOTE = 'VOTE';
export const VOTE_ERROR = 'VOTE_ERROR';

